Metrics/ModuleLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
