AllCops:
  TargetRubyVersion: 2.6

Metrics/ModuleLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Lint/DuplicateMethods:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
